//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-L3GONP2;Initial Catalog=VehicleShowroomManagementSystem;User " +
            "ID=sa;Password=rtyfghvbn2")]
        public string VehicleShowroomManagementSystemConnectionString {
            get {
                return ((string)(this["VehicleShowroomManagementSystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAB08-PC03;Initial Catalog=VehicleShowroomManagementSystem;Persist Se" +
            "curity Info=True;User ID=sa;Password=1234$")]
        public string VehicleShowroomManagementSystemConnectionString3 {
            get {
                return ((string)(this["VehicleShowroomManagementSystemConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAB08-PC03;Initial Catalog=VehicleShowroomManagementSystem;User ID=sa" +
            ";Password=1234$")]
        public string VehicleShowroomManagementSystemConnectionString1 {
            get {
                return ((string)(this["VehicleShowroomManagementSystemConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-JTM46PS;Initial Catalog=VehicleShowroomManagementSystem;Persi" +
            "st Security Info=True;User ID=thangpham;Password=1234")]
        public string VehicleShowroomManagementSystemConnectionString4 {
            get {
                return ((string)(this["VehicleShowroomManagementSystemConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-L3GONP2;Initial Catalog=VehicleShowroomManagementSystem;User " +
            "ID=thangpham;Password=rtyfghvbn2")]
        public string VehicleShowroomManagementSystemConnectionString2 {
            get {
                return ((string)(this["VehicleShowroomManagementSystemConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-ELRATTB;Initial Catalog=VehicleShowroomManagementSystem;User " +
            "ID=sa;Password=rtyfghvbn2")]
        public string VehicleShowroomManagementSystemConnectionString5 {
            get {
                return ((string)(this["VehicleShowroomManagementSystemConnectionString5"]));
            }
        }
    }
}
